export enum ActionTypes {
  DELETE_TODO = "DELETE_TODO",
  ADD_TODO = "ADD_TODO",
  TOGGLE_TODO = "TOGGLE_TODO",
  COMPLETE_ALL_TODO = "COMPLETE_ALL_TODO",
  UNCOMPLETE_ALL_TODO = "UNCOMPLETE_ALL_TODO",
  DELETE_ALL_TODO = "DELETE_ALL_TODO"
}
